name: jtest testing
on: workflow_dispatch
jons:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: downloading repo
        uses: actions/checkout@v3
      - name: initating the npm
        run: |
          npm ci
      - name: initating the testing
        run: |
          npm test
