name: jtest testing
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: downloading repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: initating the testing
        run: npm test
      - name : Sending email
        run : |
          sudo apt install mailutils -y
          echo "test body of the email" | mail -s 'test subject' ganeshsonawane5896@gmail.com
