name: jtest testing
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: downloading repo
        uses: actions/checkout@v3
      - name: install vitest
        run: |
          npm install vitest
          npm i --save-dev vitest
      - name: initating the testing
        run: vitest run 
          
