name: jtest testing
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: downloading repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: initating the testing
        run: npm test
  sync-branch:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test to main merging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: test_branch
          target_branch: main
          github_token: ${{ github.token }}
